server:
  servlet:
    context-path: /authentic/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Authentic?currentSchema=Authentic
    username: postgres
    password: 1998
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: MinhaChaveSuperSecreta123 # substitua por sua chave secreta real
  expiration: 60000  # 1 minutos em milissegundos

logging:
  level:
    org:
      hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
